export const accounts = [
  "arrow-indent",
  "bill",
  "calendar",
  "campus",
  "contact-card",
  "editor",
  "integration-connected",
  "integration-disconnected",
  "integrations",
  "lightbulb",
  "photo",
  "renew",
  "safe",
  "stamp",
];
