export const registrations = [
  "add-ons",
  "assignments",
  "attendee-type",
  "bell",
  "calendar-outline",
  "capacity",
  "discount",
  "drag",
  "form-download",
  "overview",
  "person-details",
  "put-back-arrow",
  "refund",
  "reports",
  "scholarship",
  "undo",
];
